### PR TITLE
replace parsing of $CLIBD/symop.lib with sgtbx

### PR DESCRIPTION
**Pull request by rjgildea**

### CODE REVIEW

**Comment by graeme-winter** [comment]
Looked through the code changes, they all look sensible. Ran a test, seems to do what I would expect with the code in the branch. One concern I have is the handling of R3:H vs. H3 etc. - I know this can be a _thing_. Have you a test case for this?

**Comment by graeme-winter** [comment]
I do note that this now means fast_dp does _not_ run on Python3 - possibly it could do? Maybe an absolute imports thing.

**Review by graeme-winter — APPROVED** [review]
Definite improvement, works for the use cases which were causing issues last week. Also tested with fast_rdp which seemed to do "the right thing"

**Comment by graeme-winter** [comment]
Travis test failure reflects previous lack of testing not a new problem - the issue is highlighted by the adding of tests.

**Comment by Anthchirp** [comment]
fast_dp will not run on python3 as it now depends on cctbx more than it did before.

**Comment by rjgildea** [comment]
> I do note that this now means fast_dp does _not_ run on Python3 - possibly it could do? Maybe an absolute imports thing.

> fast_dp will not run on python3 as it now depends on cctbx more than it did before.

As far as I can tell fast_dp already depended on sgtbx in a number of places, e.g. when parsing the pointless xml output:
https://github.com/DiamondLightSource/fast_dp/blob/e84509d5358fb1cbf7888e3eb0aeb97d0930e796/fast_dp/pointless_reader.py#L27-L33

or when the --cell option is set:
https://github.com/DiamondLightSource/fast_dp/blob/fef9316ff9ae4d7aacbd0840970f6804c5d4b857/fast_dp/cell_spacegroup.py#L245-L254

**Comment by rjgildea** [comment]
@graeme-winter r.e. 

> One concern I have is the handling of R3:H vs. H3 etc. - I know this can be a _thing_. Have you a test case for this?

```
$ dials.python
Python 2.7.16 (default, Apr  3 2019, 15:01:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fast_dp import cell_spacegroup
>>> cell_spacegroup.check_spacegroup_name("H3")
'R 3 :H'
>>> cell_spacegroup.check_spacegroup_name("R3:H")
'R 3 :H'
>>> cell_spacegroup.ersatz_pointgroup("H3")
'R 3'
```
Is this the behaviour you expect?

**Comment by graeme-winter** [comment]
@rjgildea not sure, will review what it used to do and get back to you

**Comment by graeme-winter** [comment]
Reviewing

```
>>> cs.ersatz_pointgroup('H3')
'R3'
>>> cs.ersatz_pointgroup('R32')
'R32'
>>> cs.ersatz_pointgroup('H32')
'R321'
>>> cs.ersatz_pointgroup('H3')
'R3'
>>> reload(cs)
<module 'fast_dp.cell_spacegroup' from '/Users/graeme/svn/cctbx/modules/fast_dp/fast_dp/cell_spacegroup.py'>
>>> cs.ersatz_pointgroup('H3')
'R 3'
>>> cs.ersatz_pointgroup('R32')
'R 3 2'
>>> cs.ersatz_pointgroup('H32')
'R 3 2'
```

reload was checking out `sgtbx` branch - first 3 calls on master. Looks like the end game is more spaces and fewer rustic bugs, so happy.

**Pull request merged**
